#ddev-generated
hooks:
  post-start:
    - exec: "sudo chown $DDEV_USER ~/.cache/ms-playwright"
    - exec: "npx playwright install"

# Allows connection to the X server on the host machine for GUI applications.
web_environment:
  - DISPLAY=:0

